spring:
  application:
    name: queue-system
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/laborwaze}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:dev2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false          # adicionado
    properties:
      hibernate:
        format_sql: true
        # dialect removido — Hibernate detecta automaticamente
  flyway:
    enabled: true
    locations: classpath:db/migration
  websocket:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:JNC72mO11+vzeSWHjvgUa5T1fvfWxIfTB/B86LK1/hw=}
    expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html