ALTER TABLE pacientes         ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE salas             ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE usuarios          ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE setores           ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE servicos          ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE chamadas          ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tentativas_chamada ADD COLUMN version BIGINT NOT NULL DEFAULT 0;